nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000', 'http://127.0.0.7:5500', 'http://localhost:5173', 'https://fittrackapp.vercel.app']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Set-Cookie']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000', 'http://127.0.0.7:5500', 'http://localhost:5173', 'https://fittrackapp.vercel.app']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Set-Cookie']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_credentials: true
            max_age: 3600
