controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/users/signIn

app.swagger_ui:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger_ui